=== ces3-2023-1/Universidades/src/resources/Pedido.dtd
<!ELEMENT pedidos (pedido+)>
        <!ELEMENT pedido  (fecha_entrega, fecha_creacion, transportista,cliente, direccion,cometario? ,productos)>
        <!ATTLIST pedido numero_pedido ID #REQUIRED>
        <!ELEMENT fecha_entrega (#PCDATA)>
        <!ELEMENT fecha_creacion (#PCDATA)>
        <!ELEMENT transportista (#PCDATA)>
        <!ELEMENT cliente (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT cometario (#PCDATA)>
        <!ELEMENT productos (producto+)>
        <!ELEMENT producto (nombre, precio, cantidad)>
        <!ATTLIST producto cod_producto CDATA #REQUIRED
                categoria (Suplemento | Medicamento | Naturista )  #REQUIRED >
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT precio (#PCDATA)>
        <!ELEMENT cantidad (#PCDATA)>

=== ces3-2023-1/Universidades/src/resources/Peidido.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pedidos SYSTEM "Pedido.dtd">
<pedidos>
    <pedido numero_pedido="A123" >

        <fecha_entrega>2023-04-08</fecha_entrega>
        <fecha_creacion>2023-04-05</fecha_creacion>
        <transportista>Servientrega</transportista>
        <cliente>Cristiano Ronaldo</cliente>
        <direccion>Cll 89</direccion>
        <productos>
            <producto cod_producto="2" categoria="Suplemento">
                <nombre>Proteina</nombre>
                <precio>70000</precio>
                <cantidad>1</cantidad>
            </producto>
        </productos>
    </pedido>
    <pedido numero_pedido="A12">
        <fecha_entrega>2023-04-08</fecha_entrega>
        <fecha_creacion>2023-04-03</fecha_creacion>
        <transportista>Diego Villegas</transportista>
        <cliente>Juan Perez</cliente>
        <direccion>Regional 120A</direccion>
        <cometario>Entrega importante</cometario>
        <productos>
            <producto cod_producto="P1" categoria="Medicamento">
                <nombre>Gotas Ojos</nombre>
                <precio>3500</precio>
                <cantidad>2</cantidad>
            </producto>
            <producto cod_producto="2" categoria="Suplemento">
                <nombre>Proteina</nombre>
                <precio>70000</precio>
                <cantidad>1</cantidad>
            </producto>
            <producto cod_producto="3" categoria="Naturista">
                <nombre>Litio</nombre>
                <precio>20000</precio>
                <cantidad>1</cantidad>
            </producto>
        </productos>

    </pedido>
</pedidos>
