=== ces3-2023-1/Universidades/src/resourses/noImporta/Estudiante.dtd
<!ELEMENT estudiantes (estudiante)>
        <!ELEMENT estudiante (edad?,comentario*,materias?)>
        <!ATTLIST estudiante nombre #PCDATA>
        <!ELEMENT edad (#PCDATA)>
        <!ELEMENT comentario (#PCDATA)>
<!ELEMENT materias (materia+)>
        <!ELEMENT materia (codigo?,nombreMat?,estado?)>
        <!ATTLIST materia codReg #PCDATA>
        <!ELEMENT codigo (#PCDATA)>
        <!ELEMENT nombreMat (#PCDATA)>
        <!ELEMENT estado (#PCDATA)>

=== ces3-2023-1/Universidades/src/resourses/Estudiante.xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>

<!DOCTYPE estudiantes SYSTEM "Estudiante.dtd" >

<estudiantes>
    <!-- Este es un comentario -->
    <estudiante nombre="Elian Ruiz">
        <edad>21</edad>
        <comentario>El codigo da error</comentario>
        <materias>
            <materia codReg="TMR000033">
                <codigo>ING20</codigo>
                <nombreMat>Ingenieria de software</nombreMat>
                <estado>True</estado>
            </materia>

            <materia codReg="TMR000433">
                <codigo>ING23</codigo>
                <nombreMat>Comunicacion audiovisual</nombreMat>
                <estado>False</estado>
            </materia>
        </materias>
    </estudiante>
</estudiantes>
