=== ces3-2023-1/Universidades/src/main/resources/estudiantes.dtd
<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (edad,materias?)>
<!ATTLIST estudiante nombre CDATA #REQUIRED>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT materias (materia)>
<!ELEMENT materia (nombre,activo)>
<!ATTLIST materia codigo CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT activo (#PCDATA)>

=== ces3-2023-1/Universidades/src/main/resources/estudiantes.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE estudiantes SYSTEM "estudiantes.dtd">

<estudiantes>
    <estudiante nombre="Camilo">
        <edad>20</edad>
        <materias>
            <materia codigo="001">
                <nombre>CES3</nombre>
                <activo>true</activo>
            </materia>
        </materias>
    </estudiante>
    <estudiante nombre="Oscar">
        <edad>21</edad>
    </estudiante>
</estudiantes>
