=== ces3-2023-1/Universidades/src/resourses/Servicio.dtd
<!ELEMENT servicios (servicio+)>
        <!ELEMENT servicio (nombre,valor,activo)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT valor (#PCDATA)>
        <!ELEMENT activo (#PCDATA)>

=== ces3-2023-1/Universidades/src/resourses/Servicio.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE servicios SYSTEM "Servicio.dtd" >-->

<servicios xmlns:xsi="http://www.w3.org/2001/XMLSchema"
            xsi:noNamespaceSchemaLocation="Servicio.xsd">
    <servicio>
        <nombre>Peluqueria</nombre>
        <valor>20000</valor>
        <activo>false</activo>
    </servicio>
    <servicio>
        <nombre>Barberia</nombre>
        <valor>10000</valor>
        <activo>false</activo>
    </servicio>
    <servicio>
        <nombre>Uñas</nombre>
        <valor>40000</valor>
        <activo>true</activo>
    </servicio>
    <servicio>
        <nombre>Pestañas</nombre>
        <valor>35000</valor>
        <activo>true</activo>
    </servicio>
</servicios>
